parameters:
  - name: BuildName
    type: string
  - name: BuildCommandLine
    type: string
  - name: WorkingDirectory
    type: string
  - name: Condition
    type: string
    default: succeeded()
  - name: ExtraAnyBuildArgs
    type: string
    default: --WhyCacheMiss

steps:
- bash: |
    set -euo pipefail

    echo "===== Running '${{ parameters.BuildCommandLine }}' from $(pwd)"
    echo

    readonly abClientExe="$(Ab.AnyBuildCIDownloadDir)/$(Ab.LinuxDropArtifactName)/AnyBuild/AnyBuild"

    env -i                                                                \
      SECRET=$(LLVMPrincipalPassword)                                     \
      HOME="$HOME"                                                        \
      PATH="$PATH"                                                        \
    "$abClientExe"                                                        \
      --RemoteExecServiceUri $(AnyBuildEnvironmentUri)                    \
      --NoCheckForUpdates                                                 \
      --WaitForAgentForever                                               \
      --DoNotUseMachineUtilizationForScheduling                           \
      --ClientApplicationId $(LLVMPrincipalAppId)                         \
      --ClientSecretEnvironmentVariable SECRET                            \
      --ExperimentName "${{ parameters.BuildName }}"                      \
      ${{ parameters.ExtraAnyBuildArgs }}                                 \
      --WhyCacheMissOptions CacheDataStoreKey=${{ parameters.BuildName }} \
      --                                                                  \
      ${{ parameters.BuildCommandLine }}
  workingDirectory: ${{ parameters.WorkingDirectory }}
  displayName: AnyBuild ${{ parameters.BuildName }}
  condition: ${{ parameters.Condition }}

- template: ./print-anybuild-stats.yml
  parameters:
    LogsDir: ${{ parameters.WorkingDirectory }}
    Condition: ${{ parameters.Condition }}