parameters:
- name: LogsDir
  type: string
- name: Condition
  type: string
  default: succeeded()

steps:
- bash: |
    set -euo pipefail

    readonly logFile="${{ parameters.LogsDir }}/AnyBuild.log"
    if [[ -f "$logFile" ]]; then
      echo "=== AnyBuild stats ==="
      sed -n '/Session telemetry: Finished/,$ p' "$logFile"
    fi
  continueOnError: true
  condition: ${{ parameters.Condition }}
  displayName: Print AnyBuild Stats